# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - shell: bash
      run: |
        mkdir -p ../../Framework/archive/build/jar
        curl https://jenkins.runsafe.no/job/Framework/lastSuccessfulBuild/artifact/build/jar/framework.jar -o ../../Framework/archive/build/jar/framework.jar
        cd ../../Framework
        git clone git@github.com/runsafe/Framework
        mv Framework workspace
    - name: Build with Ant
      run: ant -noinput -buildfile ant.xml
